export type Complexity = "S" | "M" | "L" | "XL";
export type Status = "pending" | "deployed" | "done";

export interface Task {
  id: string;
  title: string;
  complexity: Complexity;
  description: string;
  status: Status;
  version?: string;
}

export interface Section {
  label: string;
  tasks: Task[];
}

export const sections: Section[] = [
  {
    label: "Drivers",
    tasks: [
      { id: "KF1-D-01", title: "Make columns sortable",       complexity: "S", status: "done", version: "v6.0.3beta", description: "Click column headers to sort by any stat with ascending/descending toggle." },
      { id: "KF1-D-02", title: "Filter to current drivers",   complexity: "S", status: "done", version: "v6.0.4beta", description: "Toggle to show only drivers active in the current season." },
      { id: "KF1-D-03", title: "Filter Indy 500 drivers out", complexity: "S", status: "done", version: "v6.0.3beta", description: "Hide drivers whose only appearances were the Indianapolis 500 rounds (1950–1960)." },
      { id: "KF1-D-05", title: "Flag icons",                  complexity: "S", status: "done", version: "v6.0.5beta", description: "Show a nationality flag beside each driver using ISO country codes from the nationalities table." },
      { id: "KF1-D-06", title: "Poles column",                complexity: "S", status: "done", version: "v6.0.4beta", description: "Add a pole positions column to the drivers list." },
      { id: "KF1-D-07", title: "Fastest laps column",         complexity: "S", status: "done", version: "v6.0.4beta", description: "Add a fastest laps column to the drivers list." },
      { id: "KF1-D-08", title: "Champion icons",              complexity: "S", status: "done", version: "v6.0.5beta", description: "Show a visual indicator beside drivers who have won a World Championship." },
      { id: "KF1-D-09", title: "Championships count",         complexity: "S", status: "done", version: "v6.0.5beta", description: "Show the number of World Championships won on the drivers list and detail pages." },
      { id: "KF1-D-10", title: "Ranks to statistics",         complexity: "S", status: "done", version: "v6.0.9beta", description: "Show each driver's all-time rank for wins, podiums, points, poles, and fastest laps on the driver detail stat cards. Rank is hidden for zero values." },
      { id: "KF1-D-12", title: "Full results breakdown",      complexity: "M", status: "done", version: "v6.0.9beta", description: "Expandable season rows on the driver detail page showing each race with title (fullTitle if set, else '{year} {adjective} Grand Prix' using nationality adjective from DB, or '{year} Indianapolis 500'; US races use 'United States' not 'American'), grid, finish, fastest lap (purple FL column), and points. Race titles link to individual race pages. Fixed stale race page cache — all 1171 races fully generated." },
      { id: "KF1-D-BUG-01", title: "Bug: Spurious 0s after driver names", complexity: "S", status: "done", version: "v6.0.4beta", description: "MySQL returns tinyint(1) fields as 0/1 numbers; JSX short-circuit {0 && <span>} renders a literal 0. Fixed by coercing to Boolean() in page.tsx map." },
      { id: "KF1-D-BUG-02", title: "Bug: Flag icons not showing",          complexity: "S", status: "done", version: "v6.0.6beta", description: "Flag icons not displaying on the drivers list. CDN link is in layout but flags are absent — likely a CSS class or code path issue." },
      { id: "KF1-D-BUG-03", title: "Bug: Senna shows 2 championships (should be 3)", complexity: "S", status: "done", version: "v6.0.7beta", description: "Championship count query returning 2 for Senna instead of 3. Root cause: 1988 raw points gave Prost the win (105 vs 94); fixed by applying the 'best N results' drop rule per season via seasonPtsCTE() with window functions." },
      { id: "KF1-D-BUG-04", title: "Bug: No numbers in poles/fastest laps on driver page", complexity: "S", status: "done", version: "v6.0.6beta", description: "Poles and Fastest Laps stat cards on the individual driver page are showing blank instead of numbers." },
      { id: "KF1-D-BUG-05", title: "Bug: Death date showing for living drivers", complexity: "S", status: "done", version: "v6.0.6beta", description: "The date of death is appearing on driver detail pages for drivers who are still alive. Likely a null check issue." },
      { id: "KF1-D-FIX-01", title: "Fix: Championship stars in own left column", complexity: "S", status: "done", version: "v6.0.6beta", description: "Move championship stars to a dedicated sortable column on the left of the table, removing the separate championships count column." },
      { id: "KF1-D-FIX-02", title: "Fix: Remove number next to stars on driver page", complexity: "S", status: "done", version: "v6.0.6beta", description: "The Championships stat card shows '★★★ 3' — the number is redundant. Show stars only." },
      { id: "KF1-D-ENH-01", title: "Flag icon on driver detail page",      complexity: "S", status: "done", version: "v6.0.6beta", description: "Show the driver's nationality flag on their individual page alongside the nationality text." },
      { id: "KF1-D-ENH-02", title: "Current/Indy indicator on driver page", complexity: "S", status: "done", version: "v6.0.6beta", description: "Show a 'Current' or 'Indy' badge on the individual driver detail page header." },
      { id: "KF1-D-ENH-03", title: "Teammates per year in season table",   complexity: "S", status: "done", version: "v6.0.7beta", description: "On the driver detail page, show teammate name(s) alongside each season row in the season-by-season breakdown." },
      { id: "KF1-D-ENH-04", title: "Championship position in season table", complexity: "S", status: "done", version: "v6.0.7beta", description: "Show the driver's final championship standing (e.g. P1, P2) for each season in the season-by-season table." },
      { id: "KF1-D-BUG-06", title: "Bug: Incorrect nationality text for some drivers", complexity: "S", status: "done", version: "v6.0.8beta", description: "Some drivers show the correct flag but wrong nationality label — e.g. Leclerc shows the Monaco flag but says 'Australian'. Fixed by updating the adjective field in the nationalities table for 15 nationalities including Monaco (Monegasque), Netherlands (Dutch), Uruguay, Azerbaijan, and others." },
      { id: "KF1-D-ENH-05", title: "Default sort by last name on drivers list", complexity: "S", status: "done", version: "v6.0.8beta", description: "Change the default sort order on the all-drivers view from wins descending to surname ascending, so drivers are listed alphabetically on first load." },
      { id: "KF1-D-ENH-06", title: "Wrap championship stars onto two rows for 5+ titles", complexity: "S", status: "done", version: "v6.0.8beta", description: "Drivers with 5 stars (Fangio) or 7 stars (Schumacher, Hamilton) now show stars in two rows using a ceil/floor split (5→3+2, 7→4+3) on both the drivers list and driver detail page." },
      { id: "KF1-D-ENH-07", title: "First/last race as text with full race name", complexity: "S", status: "done", version: "v6.0.8beta", description: "On the driver detail page, First race and Last race are now shown as plain text below the stat cards with the full race name and year. Current drivers show 'Latest race' instead of 'Last race'." },
      { id: "KF1-D-ENH-08", title: "Championships box on its own row above stats", complexity: "S", status: "done", version: "v6.0.8beta", description: "On the driver detail page, the Championships banner now appears in its own amber-tinted row above the stat cards and is hidden entirely for drivers with no titles. The 7 remaining stats fit on one row." },
      { id: "KF1-D-ENH-09", title: "Redesign penalty section on driver page", complexity: "M", status: "pending", description: "Rework the penalty/incident section on the driver detail page — improve layout, visual hierarchy, and information density to make penalty history easier to read." },
      { id: "KF1-D-ENH-10", title: "First/last race: use short title not full title", complexity: "S", status: "done", version: "v6.2.0", description: "The first race and last race text on driver detail pages should display the short race title (e.g. 'Australian Grand Prix') rather than the full event title which can be very long. Applies to both drivers and constructors." },
      { id: "KF1-D-ENH-11", title: "Highlight top-3 ranks on stat boxes", complexity: "S", status: "done", version: "v6.2.0", description: "On driver (and constructor) detail pages, highlight the rank indicator on stat boxes when the driver/constructor is ranked 1st (gold), 2nd (silver), or 3rd (bronze) all-time." },
      { id: "KF1-D-ENH-12", title: "Rank boxes link to records page", complexity: "S", status: "done", version: "v6.3.2", description: "Make the '#N all-time' rank text on driver (and constructor) stat boxes a clickable link to the corresponding section of the records page. Implemented for driver pages (Races→/records/race-starts, Wins→/records/wins, Podiums, Poles, Fastest Laps, Points). Constructor pages don't have equivalent records pages yet." },
      { id: "KF1-D-ENH-13", title: "Consistent column spacing on driver pages", complexity: "S", status: "done", version: "v6.3.2", description: "Audit and standardise column widths and padding across the season-by-season table and race results expansion on driver detail pages. Fixed: explicit width classes on numeric columns; aligned inner race table (7 cols) with consistent px-2/px-3 padding." },
      { id: "KF1-D-ENH-14", title: "Driver fact card before season table", complexity: "M", status: "pending", description: "Show an auto-generated highlight fact about the driver (e.g. 'Won X consecutive races in YEAR', 'Youngest winner', 'Only driver to beat...') in a callout card between the stat boxes and the season-by-season table." },
      { id: "KF1-D-ENH-15", title: "Show which races belong to each team when driver switched mid-season", complexity: "M", status: "done", version: "v6.2.0", description: "When a driver drove for two or more teams in a single season, the expanded race list should indicate which team each race was with — while keeping all races grouped under a single year row. Currently multi-team seasons show one merged summary row with no way to see the split." },
      { id: "KF1-D-ENH-16", title: "Show = prefix on tied ranks", complexity: "S", status: "pending", description: "When two or more drivers (or constructors) share the same all-time rank (e.g. both have 12 poles), the rank indicator on stat boxes should show '=5 all-time' rather than '5 all-time'. Applies to both driver and constructor detail pages." },
      { id: "KF1-D-ENH-17", title: "Running points total and championship position in expanded season rows", complexity: "M", status: "done", version: "v6.3.2", description: "In the expanded per-race breakdown within a season row on the driver detail page, show the driver's cumulative points total and championship standing after each race, so you can see how their season unfolded. Added Cum and Chp columns to the expanded race table. New getDriverSeasonCumulative() query uses window functions to compute running totals and rank all drivers in the active seasons at each race point." },
      { id: "KF1-D-ENH-18", title: "Use short GP title in expanded season race list", complexity: "S", status: "done", version: "v6.2.0", description: "In the season-by-season expandable race list on driver pages, race titles should use the short form (e.g. 'Australian Grand Prix') rather than the full event title which can be very long and wraps poorly." },
      { id: "KF1-D-ENH-19", title: "Teammate names in season table should link to their driver page", complexity: "S", status: "done", version: "v6.2.0", description: "The teammate column in the season-by-season table on driver detail pages shows plain text names. These should be clickable links to the respective teammate's driver page." },
      { id: "KF1-D-ENH-20", title: "Nationality filter and totals row on all-drivers view", complexity: "S", status: "done", version: "v6.2.0", description: "Add a nationality dropdown filter to the all-drivers list (similar to the constructors list). Also add a totals/summary row at the bottom of the table showing aggregate stats for the current filtered set." },
      { id: "KF1-D-ENH-21", title: "Driver bios", complexity: "L", status: "pending", description: "Add a biography section to each driver detail page. Initially short text covering career highlights, notable achievements, and personal background. Source or write manually per driver." },
      { id: "KF1-D-ENH-22", title: "Move Head to Head above Season by Season on driver page", complexity: "S", status: "done", version: "v6.2.1", description: "The Head to Head section (link to comparison page) was below Season by Season on driver detail pages. Moved it above so it appears immediately after the stat boxes and first/last race info." },
      { id: "KF1-D-BUG-07", title: "Bug: Driver first/last race title wrong for races with circuitlayout_id=0", complexity: "S", status: "done", version: "v6.2.1", description: "The firstRaceTitle and lastRaceTitle subqueries used INNER JOINs on circuitlayouts/circuits/nationalities, so races with circuitlayout_id=0 were excluded. Fix: changed to LEFT JOINs with AND circuitlayout_id != 0 condition. Affected drivers like Liam Lawson whose first race was a 2023 Dutch GP (circuitlayout_id=0), causing it to erroneously show a 2024 race as first. Fix applied to both getDriverById and getConstructorById." },
    ],
  },
  {
    label: "Constructors",
    tasks: [
      { id: "KF1-C-01", title: "Make columns sortable",                complexity: "S", status: "done", version: "v6.0.10beta", description: "Click column headers on the constructors list to sort by any stat." },
      { id: "KF1-C-02", title: "Add filters",                          complexity: "S", status: "done", version: "v6.0.10beta", description: "Filter constructors by nationality, active/inactive, or era." },
      { id: "KF1-C-03", title: "Flag icons",                           complexity: "S", status: "done", version: "v6.0.10beta", description: "Show a nationality flag beside each constructor." },
      { id: "KF1-C-04", title: "Champion icons",                       complexity: "S", status: "done", version: "v6.0.10beta", description: "Visual indicator for constructors who have won the Constructors' Championship." },
      { id: "KF1-C-05", title: "More nationality data",                complexity: "S", status: "pending", description: "Expand nationality coverage — many constructors currently have no nationality set." },
      { id: "KF1-C-06", title: "Simplify multi-line displays",         complexity: "S", status: "done", version: "v6.0.12beta", description: "The driver list in season-by-season rows can be very long — truncate or collapse it." },
      { id: "KF1-C-07", title: "Full names and short names",           complexity: "S", status: "done", version: "v6.0.10beta", description: "Show both the full constructor name and short name where space allows; use short name in compact views." },
      { id: "KF1-C-08", title: "Season stats broken down by driver",   complexity: "M", status: "done", version: "v6.0.12beta", description: "Expand each season row on the constructor detail page to show each driver's individual contribution. Poles and fastest laps columns added." },
      { id: "KF1-C-09", title: "Add ranks",                           complexity: "S", status: "done", version: "v6.0.12beta", description: "Show all-time rank for each stat (races, wins, podiums, points, poles, fastest laps) on the constructor detail page stat boxes." },
      { id: "KF1-C-10", title: "History data for all teams",          complexity: "L", status: "pending", description: "Add formedFrom/became chain data for all relevant constructor lineages, not just Mercedes." },
      { id: "KF1-C-11", title: "Season table: indicate WDC and WCC champions", complexity: "S", status: "done", version: "v6.3.2", description: "In the constructor season-by-season table, mark seasons where this constructor won the Constructors' Championship (WCC), and indicate which driver won the Drivers' Championship (WDC) that year — whether or not they drove for this constructor. WCC pos shown in gold when P1; WDC winner shown as a link to their driver page." },
      { id: "KF1-C-12", title: "Move last/latest race to new line", complexity: "S", status: "done", version: "v6.2.0", description: "On constructor detail pages, the last/latest race info should appear on a separate line below the first race, consistent with the layout on driver detail pages." },
      { id: "KF1-C-13", title: "Constructor bios", complexity: "L", status: "pending", description: "Add a biography/history section to each constructor detail page. Initially can be short text sourced or written manually, covering founding, key eras, notable achievements, and current status." },
      { id: "KF1-C-14", title: "Season table: add WDC and WCC championship positions", complexity: "S", status: "done", version: "v6.3.2", description: "In the constructor season-by-season table, add columns for the constructor's final Constructors' Championship position (WCC pos) and the WDC winner for each season. WCC pos shown as P1/P2/… (gold for champion); WDC winner shown as a named link. Implemented together with C-11." },
      { id: "KF1-C-BUG-01", title: "Bug: Some constructor names not showing", complexity: "S", status: "done", version: "v6.0.6beta", description: "Constructor names are blank in some places — likely rows where both name and shortName are empty, or a JOIN returning null." },
      { id: "KF1-C-BUG-02", title: "Bug: Shanghai circuit had wrong nationality — rebuild affected pages", complexity: "S", status: "done", version: "v6.2.1", description: "The Shanghai circuit had an incorrect nationality_id in the DB (fixed by user). Pages for drivers/constructors/seasons that include the Chinese GP now rebuild correctly as 'Chinese Grand Prix'." },
      { id: "KF1-C-BUG-03", title: "Bug: Year in brackets on constructor first/last race", complexity: "S", status: "done", version: "v6.2.1", description: "Constructor detail pages were showing e.g. '2024 Australian Grand Prix (2024)' — the year was redundant because it already appears in the race title. Removed the bracketed year suffix from firstRaceTitle and lastRaceTitle display." },
      { id: "KF1-C-BUG-04", title: "Bug: Constructor stat boxes show rank when value is zero", complexity: "S", status: "done", version: "v6.2.1", description: "Constructor detail stat boxes (Wins, Podiums, Points, Poles, Fastest Laps) were showing an all-time rank even when the value was zero. Added zero-check so rank is hidden for zero-value stats, consistent with driver pages." },
    ],
  },
  {
    label: "Seasons",
    tasks: [
      { id: "KF1-S-01", title: "Champion wins and points",   complexity: "S", status: "done", version: "v6.3.2", description: "Show the champion's win count and total points alongside their name on the seasons list. Added Wins and Pts columns (champion's season wins and points, shown only for completed seasons, xs mono font). Only shown for completed seasons; in-progress seasons show nothing in those columns." },
      { id: "KF1-S-02", title: "Milestones",                 complexity: "M", status: "pending", description: "Highlight key season milestones — first win, first pole, championship clinch race, etc. on the season detail page." },
      { id: "KF1-S-ENH-01", title: "Show championship leader for current season", complexity: "S", status: "done", version: "v6.0.11beta", description: "The seasons list currently shows the points leader for the current season as if they are the champion. For the current (incomplete) season, label them as 'Leader' rather than treating them as champion." },
      { id: "KF1-S-ENH-02", title: "Show points scoring system per season", complexity: "S", status: "done", version: "v6.3.2", description: "Display the points scoring system in use for each season (e.g. 10-6-4-3-2-1 for 1991-2002, 25-18-15-12-10-8-6-4-2-1 from 2010). Added Points System column on the seasons list (rightmost, zinc-600 xs mono); added points line under season title on the season detail page. pointsSystem() utility function in queries.ts." },
      { id: "KF1-S-ENH-03", title: "Add runner-up to all seasons view", complexity: "S", status: "done", version: "v6.2.0", description: "On the seasons list page, show the Drivers' Championship runner-up alongside the champion, so you can see the top two finishers at a glance." },
      { id: "KF1-S-ENH-04", title: "Add constructor champion to all seasons view", complexity: "S", status: "done", version: "v6.2.0", description: "On the seasons list page, show the Constructors' Champion for each season (where applicable — WCC started in 1958) alongside the Drivers' Champion." },
      { id: "KF1-S-ENH-05", title: "Add poles and fastest laps to season standings", complexity: "S", status: "done", version: "v6.2.0", description: "Add pole positions and fastest laps columns to the driver standings table on the season detail page. Optionally add to the constructor standings too." },
      { id: "KF1-S-BUG-01", title: "Fix links to race results on season page", complexity: "S", status: "done", version: "v6.1.0", description: "Links to individual race results from the season detail page were returning 404. Root cause: out/races/ had only 2 pages (IDs 1 and 1156) — cache lost at some point and backup/restore preserved the minimal state. Fixed by fully rebuilding all 1084 race pages." },
      { id: "KF1-S-ENH-06", title: "Move race calendar above driver standings on season page", complexity: "S", status: "pending", description: "On season detail pages, reorder the sections so the Race Calendar (race-by-race results table) appears above the Driver Standings and Constructor Standings. Currently standings come first, which makes sense for completed seasons but feels backwards when browsing a season — you want to see the races before the summary." },
      { id: "KF1-S-BUG-02", title: "Bug: 2022 season (and 2023, 2024) showing blank screen", complexity: "S", status: "done", version: "3 Jul 2026", description: "Season pages for 2022, 2023, and 2024 show a blank/error page. Root cause: all 22 races in 2022 (and most in 2023/2024) have circuitlayout_id=0 in the grandsprix table. The getSeasonRaces query used INNER JOIN circuitlayouts which returns 0 rows when circuitlayout_id=0; if races.length === 0 then notFound() fires. Fix: change to LEFT JOIN with AND gp.circuitlayout_id != 0 condition in both getSeasonRaces and getRaceById. Also requires full seasons rebuild." },
      { id: "KF1-S-BUG-03", title: "Bug: Constructor names missing from standings on season page", complexity: "S", status: "deployed", version: "3 Jul 2026", description: "Constructor names appear blank in the driver standings and race calendar on older season pages. Investigation shows names ARE correct on 2026 (rebuilt) and 2025 pages. Root cause: seasons like 2024 and 2023 have most races with circuitlayout_id=0, so getSeasonRaces returns only 1 race — making standings look sparse/wrong. Fix: the circuitlayout_id LEFT JOIN fix (KF1-S-BUG-02) combined with a full seasons rebuild should resolve this." },
      { id: "KF1-S-BUG-04", title: "Bug: Prev/next season links not appearing", complexity: "S", status: "done", version: "3 Jul 2026", description: "Prev/next season navigation links added in v6.3.x only appear on the 2026 season page (the only season rebuilt since the feature was added). All other season pages are old backup pages without the new nav. Fix: rebuild all seasons with seasons: 'all' in .build-config.json." },
      { id: "KF1-S-BUG-05", title: "Bug: Points scoring system on season page not more prominent", complexity: "S", status: "done", version: "3 Jul 2026", description: "The points scoring system badge next to the Driver Standings heading on season pages only appears on 2026 (the only season rebuilt since the feature was added). All other season pages are old backup pages. Fix: rebuild all seasons." },
    ],
  },
  {
    label: "Comparisons",
    tasks: [
      { id: "KF1-COMP-BUG-01", title: "Bug: Comparison page lost styling",          complexity: "S", status: "done", version: "v6.0.6beta", description: "Comparison pages appear unstyled — likely caused by the cached HTML being out of date with the current CSS bundle hash after a rebuild." },
      { id: "KF1-COMP-BUG-02", title: "Bug: Some comparison pages returning 404",   complexity: "S", status: "done", version: "v6.1.0", description: "Some driver vs driver comparison pages are returning 404. Resolved by moving to per-driver comparison pages (/comparisons/[id]/) — no more pair-based generation gaps." },
      { id: "KF1-COMP-BUG-03", title: "Bug: Comparison page styling not applied",   complexity: "S", status: "done", version: "v6.0.8beta", description: "Comparison pages were losing styling after each build because Turbopack filenames are pure hashes (no name-HASH.ext pattern), so the old hash-stripping regex never matched. Fixed by positionally replacing all /_next/static/ references in cached pages using the freshly-built comparison page as the source of truth." },
      { id: "KF1-COMP-ENH-01", title: "Remove races rows from comparison table",    complexity: "S", status: "done", version: "v6.0.6beta", description: "Remove the individual race result rows from the head-to-head table to declutter the comparison view." },
      { id: "KF1-COMP-ENH-02", title: "Add qualifying comparison",                  complexity: "S", status: "done", version: "v6.0.6beta", description: "Show qualifying head-to-head (who outqualified who and by how much) for shared seasons." },
      { id: "KF1-COMP-ENH-03", title: "Add finishing position comparison",          complexity: "S", status: "done", version: "v6.1.0", description: "Show finishing position head-to-head breakdown for shared seasons." },
      { id: "KF1-COMP-ENH-04", title: "Race count next to year on comparison page", complexity: "S", status: "done", version: "v6.1.0", description: "Show the number of races in each shared season next to the year heading on the comparison page." },
      { id: "KF1-COMP-ENH-05", title: "Versus all teammates page",                  complexity: "M", status: "done", version: "v6.1.0", description: "Add a dedicated page for each driver showing aggregated head-to-head stats versus every teammate they've ever had." },
      { id: "KF1-COMP-ENH-07", title: "Comparison: show both driver counts (X - Y) for qualifying/race finish", complexity: "S", status: "done", version: "v6.2.1", description: "Changed qualifying and race finish head-to-head to show both driver counts: '4 - 2' means the driver qualified ahead 4 times, teammate ahead 2 times. Removed percentage display. Applies to both the per-season table and the summary boxes." },
      { id: "KF1-COMP-ENH-06", title: "Factor sprint races into teammate comparisons", complexity: "S", status: "pending", description: "Sprint race finishing positions should be included in the race finish head-to-head on comparison pages. Currently only the main race result is compared." },
    ],
  },
  {
    label: "Records",
    tasks: [
      { id: "KF1-R-01", title: "Full list pages per record", complexity: "S", status: "done", version: "v6.3.0", description: "Add a 'More' link on each record card to a dedicated page listing all drivers with more than 0 for that stat." },
      { id: "KF1-R-02", title: "Additional records",         complexity: "M", status: "pending", description: "Add new record categories: most grand slams (win + pole + fastest lap + led every lap), most race starts without a win, and others." },
      { id: "KF1-R-03", title: "Reformat records page into categories", complexity: "M", status: "done", version: "v6.3.1", description: "Restructure the records page into distinct sections: Most (wins, podiums, poles, fastest laps, points, races), Firsts (first win, first pole, etc.), Oldest/Youngest (oldest winner, youngest champion, etc.). Each section gets its own heading and layout." },
      { id: "KF1-R-04", title: "Indicate current drivers on records lists", complexity: "S", status: "pending", description: "On records list rows (Most tab accordion and full list pages), show a small indicator — e.g. a dot or 'Current' badge — beside drivers who are actively racing in the current season. Requires the 'current' flag from the drivers table to be returned alongside each record row." },
      { id: "KF1-R-05", title: "Consecutive records: streak status, start, and end race", complexity: "M", status: "pending", description: "Enhance each consecutive record entry to show: (a) whether the streak is still ongoing (current/active), (b) the race where the streak started (with link), and (c) the race where it ended (or a 'Ongoing' label if active). Requires updating getConsecutiveRecords() to return startGpId, startTitle, endGpId, endTitle, and an isOngoing flag alongside the streak length." },
    ],
  },
  {
    label: "Data Integrity",
    tasks: [
      { id: "KF1-DI-01", title: "Verify driver champion for every season 1950–2025",         complexity: "M", status: "pending", description: "Query computed championship standings and confirm the champion matches the known historical record for every season. Catches points logic bugs and missing results. CHECKED 1 Jul 2026 — 2 mismatches: (1) 1958: after drop rule our system picks Moss (38 pts) over Hawthorn, but Hawthorn won in reality on 42 vs 41 pts. Raw data correctly has Hawthorn at 44 pts so the drop limit or individual race results for 1958 are wrong. (2) 1979: drop rule flips result to Villeneuve (53 pts) over Scheckter, but Scheckter won on 51 vs 47 pts. Raw has Scheckter correctly at 60 pts so drop rule application for 1979 is producing wrong output. All other seasons 1950–2024 match. Needs: audit 1958 and 1979 race result data and verify drop limits." },
      { id: "KF1-DI-02", title: "Check drop-rule edge cases don't produce wrong champion",   complexity: "S", status: "pending", description: "Identify seasons where the raw points leader differs from the best-N-results leader and verify our logic picks the correct winner (e.g. 1988 Senna vs Prost). CHECKED 1 Jul 2026 — 4 seasons where drop rule changed the leader: 1958 (Hawthorn→Moss, WRONG — should stay Hawthorn), 1964 (Graham Hill→Surtees, CORRECT), 1979 (Scheckter→Villeneuve, WRONG — should stay Scheckter), 1988 (Prost→Senna, CORRECT). The 1958 and 1979 flips are bugs tied to DI-01 findings. 1964 and 1988 work correctly." },
      { id: "KF1-DI-03", title: "Verify constructor championship winners 1958–2025",         complexity: "M", status: "pending", description: "Cross-check the computed getAllConstructorChampionships() results against the known WCC winners for all seasons since the trophy was introduced. CHECKED 1 Jul 2026 — Most mismatches are name format only (Scuderia Ferrari vs Ferrari, Team McLaren vs McLaren, WilliamsF1 Team vs Williams, Lotus F1 Team vs Lotus, Red Bull Racing vs Red Bull, Mercedes GP vs Mercedes). REAL wrong champions: 1958 Vanwall (us: Ferrari), 1959 Cooper (us: Ferrari), 1962 BRM (us: Cooper), 1964 Ferrari (us: BRM), 1965 Lotus (us: BRM), 1970 Lotus (us: Ferrari), 1972 Lotus (us: McLaren), 1973 Lotus (us: Tyrrell), 1974 McLaren (us: Ferrari). Root cause: early WCC used per-race driver-count rules (only best 1–2 drivers per constructor per race scored) and a separate constructor drop rule — not implemented. 2007: McLaren won on points but were excluded from WCC by FIA (Spygate); Ferrari were awarded the title — cannot be modelled without a manual override flag. All other seasons correct once name normalisation is applied." },
      { id: "KF1-DI-04", title: "List races with missing pole times",                        complexity: "S", status: "done", version: "2 Jul 2026", description: "Query races with no entry in the poletimes table, grouped by year, to identify where qualifying time data needs to be added. CHECKED 2 Jul 2026 — only 14 missing, all future races (R9–R22, 5 Jul–6 Dec 2026). All past races clean. Previous check (1 Jul) showed 73 missing across 2023–2026; those have since been entered." },
      { id: "KF1-DI-05", title: "List races with missing fastest laps",                      complexity: "S", status: "done", version: "1 Jul 2026", description: "Query races with no entry in the fastestlaps table. Early years are expected gaps; flag anything post-1990 that looks like missing data. CHECKED 1 Jul 2026 — 2 missing: (1) 2021 Belgian GP (ID 1047) — correct, race was red-flagged after 2 laps behind the safety car, no fastest lap was awarded. (2) 2026 Austrian GP (ID 1157, R08) — needs data entry, covered by KF1-2026-R08." },
      { id: "KF1-DI-06", title: "Find drivers with missing nationality code",                complexity: "S", status: "done", version: "1 Jul 2026", description: "Query drivers whose nationalityCode is null or empty — these show blank flags on the drivers list and detail pages. CHECKED 1 Jul 2026 — all 860 drivers have valid nationality and iso2 code. Clean pass." },
      { id: "KF1-DI-07", title: "Find constructors with missing nationality",                complexity: "S", status: "pending", description: "Query constructors with null nationality_id — these show no flag on the constructors list. Relates to KF1-C-05. CHECKED 1 Jul 2026 — 121 of ~172 constructors have nationality_id=NULL/0, including every major team: Ferrari (1132 races), McLaren (1013), Williams (962), Mercedes, Lotus, Tyrrell, etc. Essentially the entire constructor list has no nationality set. Relates to KF1-C-05 (More nationality data)." },
      { id: "KF1-DI-08", title: "Find results with mismatched place/position fields",        complexity: "S", status: "pending", description: "Query results rows where place is null or non-numeric but position is valid, or vice versa. These can cause incorrect win/podium counts. CHECKED 1 Jul 2026 — Case 1 (position numeric, place=DNF/DNS/NC): 50+ results concentrated in 1950, appears intentional by design — position stores overall finishing order (including retirements), place stores classified text result. Case 2 (place set, position missing): 0 results, clean. Case 3 (both numeric but disagree): 50+ results from 1950–1952, all with position = place + 1. Systematic off-by-one in the position column for early seasons — place appears correct, position is shifted up by 1. Also 1950 France has two drivers sharing the same place value (shared drive). The position field in early seasons looks unreliable; place should be used for win/podium counts." },
      { id: "KF1-DI-09", title: "Find entrants with no results",                             complexity: "S", status: "pending", description: "Query entrant rows that have no matching results rows — may indicate orphaned data or entries that never started. CHECKED 1 Jul 2026 — 17 orphaned entrants. Notable: entrants 297–300 are four 'Renault Sport F1 Team' name variants under Renault F1 Team (id=131) with zero results; entrant 192 'Team Lotus' and entrant 236 'Marlboro Team McLaren' are unused name variants under their respective constructors. The rest are minor historical teams or name-variant orphans. All appear to be safely ignorable (data entry artefacts, not missing race data)." },
      { id: "KF1-DI-10", title: "Find races with no recorded winner",                        complexity: "S", status: "done", version: "1 Jul 2026", description: "Query races where no result row has place = '1' or position = 1. Should be zero — any hits indicate missing or malformed result data. CHECKED 1 Jul 2026 — only hit is 2026 Austrian GP (ID 1157, R08) which has no results entered yet. All prior completed races have a winner. Clean pass." },
      { id: "KF1-DI-11", title: "Find duplicate grid positions within a race",               complexity: "S", status: "pending", description: "Query races where the same grid position appears for more than one driver. Legitimate in rare cases (shared row) but worth flagging for review. CHECKED 1 Jul 2026 — 293 combinations flagged total. Breakdown: 16 are grid=99 (placeholder), 105 are pre-1960 (shared rows were standard practice). 185 are genuine post-1960 duplicates spanning 1960–2025, including recent ones: 2021 Abu Dhabi (Verstappen & Mazepin both grid 1 — Mazepin likely should be last), 2022 Australia (Stroll & Albon both grid 20), 2024 Belgium (Stroll & Hülkenberg both grid 16), 2025 Spain (Bearman & Stroll both grid 14). Pre-1980 duplicates may be intentional shared-row practice; 1980 onwards are data errors to fix." },
      { id: "KF1-DI-12", title: "Find results with points outside era scoring positions",    complexity: "M", status: "pending", description: "Query results where points > 0 but the finishing position is outside the expected points-paying range for that season's era (e.g. P11+ scoring in the 6-points era). CHECKED 1 Jul 2026 — 19 results flagged (fullPointsDriver=0 with manual points outside era range). 16 are 1950–1957 shared-drive fractional points (e.g. 1955 Argentina where Ferrari drivers split points after car sharing) — these are correct and expected. 3 are suspicious: 1967 Germany Guy Ligier P8 got 1 pt (era limit P6); 1969 Germany Siffert P11 got 2 pts and Beltoise P12 got 1 pt (both outside top-6). The 1969 German GP was curtailed by fog — may have had special points allocation, but worth verifying." },
      { id: "KF1-DI-13", title: "Find sprint results for races without sprint flag",         complexity: "S", status: "pending", description: "Query sprints table entries for grandprix rows that don't have a sprint flag set, and vice versa — sprints flagged but no sprint results recorded. CHECKED 1 Jul 2026 — The grandsprix.sprint column stores the NUMBER OF LAPS for the sprint race (0 = no sprint), not a boolean flag. 27 races have sprint data (2021–2026, 20–22 drivers each) and all correctly have sprint > 0 in grandsprix. No races with sprint data have sprint=0. No structural mismatch. ONE ANOMALY: Azerbaijan 2023 (gp#1083) has sprint=1 — likely a data entry error (should be a lap count, ~17 for Baku). All other sprint races have sensible values (17–24 laps). Note: any code using WHERE sprint = 1 would only match Azerbaijan 2023; correct filter is sprint > 0." },
      { id: "KF1-DI-14", title: "Find drivers in results with no constructor link",          complexity: "S", status: "pending", description: "Query results rows where the driver has no entrant record linking them to a constructor. These drivers would be invisible on constructor pages. CHECKED 1 Jul 2026 — 539 results total with no entrant_id or broken constructor chain. 405 are Indianapolis 500 (1950–1960) — expected, Indy entrant data was never populated. 134 are non-Indy and are real gaps, clustered by team-season: (1) 2000 — Jos Verstappen & Pedro de la Rosa, entire season (Arrow/Jaguar entrant records missing); (2) 2002 — Webber, Yoong, Sato, Fisichella, Davidson across full season (Minardi/Jordan/BAR entrants missing); (3) 2019 — Magnussen & Grosjean, entire season (Haas entrant missing); (4) individual: de Graffenried 1954 Belgium, McGuire 1976 GB, Capelli 1986 Italy+Portugal. Fix: add entrant rows for those 3 team-seasons (2000 Arrow, 2002 Minardi/Jordan/BAR, 2019 Haas)." },
      { id: "KF1-DI-15", title: "Find comparison pages that return 404",                     complexity: "M", status: "done", version: "v6.1.0", description: "Resolved by moving to per-driver comparison pages — no pair-based generation gaps possible." },
      { id: "KF1-DI-16", title: "Cross-check top driver stats against official records",     complexity: "M", status: "pending", description: "For 5–10 well-known drivers (Hamilton, Schumacher, Senna, Prost, Verstappen etc.) compare our computed wins, poles, points, and championships against Wikipedia/official F1 stats." },
      { id: "KF1-DI-17", title: "Cross-check top constructor stats against official records", complexity: "M", status: "pending", description: "For top constructors (Ferrari, Mercedes, Red Bull, McLaren, Williams) compare our computed wins, poles, points, and championships against official records." },
    ],
  },
  {
    label: "2026 Race Data",
    tasks: [
      { id: "KF1-2026-R07", title: "Enter results: R7 Spanish GP (14 Jun)",        complexity: "S", status: "done",    version: "14 Jun 2026", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Spanish Grand Prix (grandprix id 1156, 14 June 2026)." },
      { id: "KF1-2026-R08", title: "Enter results: R8 Austrian GP (28 Jun)",        complexity: "S", status: "done", version: "1 Jul 2026", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Austrian Grand Prix (grandprix id 1157, 28 June 2026)." },
      { id: "KF1-2026-R09", title: "Enter results: R9 British GP (5 Jul)",           complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 British Grand Prix (grandprix id 1158, 5 July 2026)." },
      { id: "KF1-2026-R10", title: "Enter results: R10 Belgian GP (19 Jul)",         complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Belgian Grand Prix (grandprix id 1159, 19 July 2026)." },
      { id: "KF1-2026-R11", title: "Enter results: R11 Hungarian GP (26 Jul)",       complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Hungarian Grand Prix (grandprix id 1160, 26 July 2026)." },
      { id: "KF1-2026-R12", title: "Enter results: R12 Dutch GP (23 Aug)",           complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Dutch Grand Prix (grandprix id 1161, 23 August 2026)." },
      { id: "KF1-2026-R13", title: "Enter results: R13 Italian GP (6 Sep)",          complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Italian Grand Prix (grandprix id 1162, 6 September 2026)." },
      { id: "KF1-2026-R14", title: "Enter results: R14 Spanish GP (13 Sep)",         complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Spanish Grand Prix (grandprix id 1163, 13 September 2026)." },
      { id: "KF1-2026-R15", title: "Enter results: R15 Azerbaijan GP (26 Sep)",      complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Azerbaijan Grand Prix (grandprix id 1164, 26 September 2026)." },
      { id: "KF1-2026-R16", title: "Enter results: R16 Singapore GP (11 Oct)",       complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Singapore Grand Prix (grandprix id 1165, 11 October 2026)." },
      { id: "KF1-2026-R17", title: "Enter results: R17 United States GP (25 Oct)",   complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 United States Grand Prix (grandprix id 1166, 25 October 2026)." },
      { id: "KF1-2026-R18", title: "Enter results: R18 Mexico City GP (1 Nov)",      complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Mexico City Grand Prix (grandprix id 1167, 1 November 2026)." },
      { id: "KF1-2026-R19", title: "Enter results: R19 São Paulo GP (8 Nov)",        complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 São Paulo Grand Prix (grandprix id 1168, 8 November 2026)." },
      { id: "KF1-2026-R20", title: "Enter results: R20 Las Vegas GP (21 Nov)",       complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Las Vegas Grand Prix (grandprix id 1169, 21 November 2026)." },
      { id: "KF1-2026-R21", title: "Enter results: R21 Qatar GP (29 Nov)",           complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Qatar Grand Prix (grandprix id 1170, 29 November 2026)." },
      { id: "KF1-2026-R22", title: "Enter results: R22 Abu Dhabi GP (6 Dec)",        complexity: "S", status: "pending", description: "Enter race results, grid positions, fastest lap, and sprint results (if any) for the 2026 Abu Dhabi Grand Prix (grandprix id 1171, 6 December 2026)." },
    ],
  },
  {
    label: "Site",
    tasks: [
      { id: "KF1-X-01", title: "Data validation",       complexity: "M", status: "pending", description: "Audit all data for accuracy — cross-check points totals, standings, race results, and pole positions against official sources." },
      { id: "KF1-X-02", title: "Test all functionality", complexity: "M", status: "pending", description: "Full functional test pass across all pages and edge cases: missing data, single-race constructors, shared drives, DNS/DNQ entries." },
      { id: "KF1-X-03", title: "Remote triggers for build/deploy", complexity: "S", status: "pending", description: "Set up Claude Code remote triggers so builds and deployments can be kicked off from a phone via claude.ai. At minimum: race update trigger (runs build:race then deploy) and full build trigger." },
      { id: "KF1-X-04", title: "Add missing pole times", complexity: "M", status: "pending", description: "The poletimes table is missing qualifying time data for many races. Research and populate missing pole times so they display correctly on race pages and in constructor/driver stats." },
      { id: "KF1-X-05", title: "Sort out Indy 500 results, teams, and displays", complexity: "L", status: "pending", description: "The Indianapolis 500 races (1950–1960) have various display and data issues: drivers marked indyOnly may show incorrectly in stats, constructor entries may be incomplete, race titles and result displays need auditing. Decide on a consistent approach for how Indy-only entries appear across drivers, constructors, seasons, and records pages." },
      { id: "KF1-X-06", title: "Add qual lap record and race lap record to circuit layouts", complexity: "M", status: "pending", description: "Add qualifying lap time record and race lap time record columns to the circuitlayouts table (e.g. qualLapRecord, qualLapRecordHolder, qualLapRecordYear, raceLapRecord, raceLapRecordHolder, raceLapRecordYear). Populate data for modern circuits. Display on race pages alongside the circuit name and city, so each race page shows the circuit's all-time qualifying and race lap records for context." },
      { id: "KF1-X-BUG-01", title: "Bug: Milestones not appearing on race pages", complexity: "S", status: "done", version: "v6.4.0", description: "Race milestone sections (added in v6.3.x) only appear on race 1157 (the Austrian GP, the only race rebuilt since the feature was added). All other race pages are old backup pages without milestones. Fix: rebuild all races with races: 'all' in .build-config.json. Note: full race rebuild covers 1170+ pages and takes significantly longer than a season rebuild." },
      { id: "KF1-X-BUG-02", title: "Bug: Prev/next race links not appearing on race pages", complexity: "S", status: "done", version: "v6.4.0", description: "Prev/next race navigation links (added in v6.3.x) only appear on race 1157. All other race pages are old backup pages without the navigation. Fix: rebuild all races. Can be combined with KF1-X-BUG-01 in a single full race rebuild pass." },
    ],
  },
];

export const deployed: { version: string; changes: string[] }[] = [
  {
    version: "v6.4.0",
    changes: [
      "Records: Consecutive tab added with accordion + full list pages for Wins (3+), Podiums (3+), Poles (3+), Fastest Laps (3+), Points Finishes (3+), Finishes (10+), Race Starts (25+)",
      "Constructor pages: WDC column removed from outer season table; per-driver WDC finishing position added to expanded driver rows",
      "Season pages: Prev/next season navigation links added to all 77 season pages",
      "Season pages: Points scoring system badge shown prominently next to Driver Standings heading on all season pages",
      "Race pages: Prev/next race navigation links added",
      "Race pages: Milestones section added (starts, wins, podiums, poles, fastest laps, career points at key thresholds)",
      "Bug fix: 2022, 2023, and 2024 season pages no longer blank — circuitlayout_id=0 INNER JOIN changed to LEFT JOIN in getSeasonRaces and getRaceById",
      "Build: Backlog mode added — set mode: 'backlog' in .build-config.json for fast backlog-only builds (~28 pages vs 135+)",
    ],
  },
  {
    version: "v6.3.2",
    changes: [
      "Driver pages: Rank boxes (#N all-time) are now clickable links to the corresponding records page category",
      "Driver pages: Consistent column widths and padding in season table and expanded race list (explicit w-10/w-12/w-14 classes)",
      "Driver pages: Expanded race rows now show Cum (cumulative season points) and Chp (championship position) columns after each race",
      "Constructor pages: WCC column added to season table — position shown as P1/P2/… with P1 highlighted in gold",
      "Constructor pages: WDC column added to season table — WDC winner shown as a link to their driver page",
      "Seasons list: Wins and Pts columns added showing champion's season win count and points (completed seasons only)",
      "Seasons list: Points System column added showing the scoring system for each season",
      "Season detail page: Points scoring system shown below the season title",
    ],
  },
  {
    version: "v6.3.1",
    changes: [
      "Records: Youngest tab — top 10 for winner, podium, pole, fastest lap, points scorer, and race starter (age at first achievement)",
      "Records: Oldest tab — top 10 for same six categories (age at last achievement)",
      "Records: Age displayed as years + days (e.g. 18y 232d) with date of the achievement",
      "Records: If no current grid driver appears in the top 10, nearest current driver shown below a divider at their actual rank",
    ],
  },
  {
    version: "v6.3.0",
    changes: [
      "Records: Tabbed layout with Most, Youngest, Oldest, Consecutive, and Other tabs",
      "Records: All existing records moved under Most tab as collapsible accordion sections",
      "Records: Each section shows top 10 on expand with current leader visible in header when collapsed",
      "Records: Full list pages added at /records/[category]/ for all six Most categories",
      "Records: Points full list page retains sortable columns (historical and 2026 system)",
    ],
  },
  {
    version: "v6.2.1",
    changes: [
      "Comparisons: Changed qualifying/race finish format from '4 — 6' to '4 - 2' (both driver counts shown, no percentage)",
      "Driver pages: Head to Head section moved above Season by Season",
      "Driver pages: Fix firstRaceTitle/lastRaceTitle skipping races with circuitlayout_id=0 (e.g. Lawson 2023 Dutch GP now correct)",
      "Constructor pages: Removed redundant year in brackets from first/last race display",
      "Constructor pages: Stat boxes no longer show rank when value is zero",
      "DB: Dutch Grand Prix shortTitle fixed (was 'Holland' → 'Dutch'); 2026 Dutch GP fullTitle cleared",
      "DB/rebuild: Chinese Grand Prix pages rebuilt after circuit nationality fix",
    ],
  },
  {
    version: "v6.2.0",
    changes: [
      "Driver pages: First/last race now uses short title (e.g. 'Australian Grand Prix') instead of full event title",
      "Driver pages: Race titles in expanded season list use short format (no year prefix, no full event title)",
      "Driver pages: Teammate names in season table are now clickable links to their driver pages",
      "Driver pages: Multi-team seasons show constructor headers in expanded race list",
      "Driver pages: Rank boxes highlighted gold/silver/bronze for top-3 all-time ranks",
      "Constructor pages: First/last race shown on separate lines; rank boxes highlighted gold/silver/bronze",
      "Constructor pages: First/last race uses short title format",
      "Seasons list: Runner-up column added; WCC (Constructor Champion) column added",
      "Season detail: Poles and FL shown on driver standings cards (hidden when zero)",
      "Comparisons: Qualifying and race finish changed from '4/6' to '4 — 6' format",
      "Drivers list: Nationality dropdown filter added; totals row at bottom of table",
    ],
  },
  {
    version: "v6.1.0",
    changes: [
      "Comparisons: Completely redesigned — one page per driver at /comparisons/[id]/ replacing all pair-based pages",
      "Comparisons: Shows aggregate shared races, qualifying ahead %, and race finish ahead % vs all teammates",
      "Comparisons: Breakdown by teammate (reverse chronological), within each teammate a per-season table",
      "Comparisons: Qualifying, race finish, and points comparison per season; total row when multiple seasons shared",
      "Driver pages: Teammates section replaced with single 'Head to Head' link to comparison page",
    ],
  },
  {
    version: "v6.0.12beta",
    changes: [
      "Constructor pages: Season-by-season table now has expandable rows showing each driver's individual stats (races, wins, podiums, poles, fastest laps, points)",
      "Constructor pages: Poles and Fastest Laps columns added to season table",
      "Constructor pages: Stat boxes now show all-time rank (#N all-time) for races, wins, podiums, points, poles, and fastest laps",
      "Constructor pages: First/Last season moved from boxes to plain text below the stat grid; Poles and Fastest Laps boxes added in their place",
    ],
  },
  {
    version: "v6.0.11beta",
    changes: [
      "Seasons list: current/incomplete season shows 'Leader' badge instead of treating leader as champion",
      "Season detail page: 'In Progress' badge in header; standings sections labelled '(In Progress)' when season not yet complete",
      "Drivers list & driver pages: championship stars now only count completed seasons (current season leader no longer shown as champion)",
      "Constructors list & constructor pages: WCC stars now only count completed seasons",
      "Fixed: module factory error on All Drivers page (stale list page now refreshed after each partial build)",
    ],
  },
  {
    version: "v6.0.10beta",
    changes: [
      "Constructors list: sortable columns (click any header)",
      "Constructors list: nationality dropdown filter, current-only toggle, Indy 500 toggle (hidden by default)",
      "Constructors list: nationality flag icons",
      "Constructors list: WCC championship stars (★ per title, stacked for 4+)",
      "Constructors list: full name as primary link, short name shown below when it differs",
      "Constructors list: poles column added",
      "Constructors list: default sort by name A→Z",
    ],
  },
  {
    version: "v6.0.9beta",
    changes: [
      "Driver pages: All-time rank shown on each stat card (wins, podiums, points, poles, fastest laps) — hidden for zero values",
      "Driver pages: Season rows now expandable to show race-by-race results (race name, grid, finish, fastest lap, points)",
      "Driver pages: Race titles use nationality adjective (e.g. 'Australian Grand Prix' not 'Australia Grand Prix'); US races show 'United States Grand Prix'; Indianapolis 500 preserved as-is",
      "Driver pages: Purple FL column in race results where fastest lap was set",
      "Race pages: Fixed stale cache — all 1171 race pages now generated and linked correctly",
    ],
  },
  {
    version: "v6.0.8beta",
    changes: [
      "Drivers: Default sort changed to surname A→Z",
      "Drivers: Championship stars wrap to two rows for 5+ titles (ceil/floor split)",
      "Driver pages: Championship banner shown in own amber row above stats; hidden if no titles",
      "Driver pages: First/last race shown as plain text with full race name; current drivers say 'Latest race'",
      "Driver pages: Nationality text fixed for 15 nationalities (Monegasque, Dutch, etc.)",
      "Comparison pages: CSS/JS hash patching fixed — positional replacement now works reliably with Turbopack",
    ],
  },
  {
    version: "v6.0.7beta",
    changes: [
      "Driver pages: Senna now correctly shows 3 championships (best-N-results drop rule applied)",
      "Driver pages: Season table now shows championship position (P1, P2, etc.) per season",
      "Driver pages: Season table now shows teammate name(s) per season",
    ],
  },
  {
    version: "v6.0.6beta",
    changes: [
      "Drivers: Flag icons now showing (local assets, ISO 2-letter codes added to DB)",
      "Drivers: Championship stars moved to dedicated sortable leftmost column",
      "Drivers: Stars-only on driver detail page (removed redundant number)",
      "Driver pages: Flag icon shown alongside nationality text",
      "Driver pages: Current / Indy 500 only badge in header",
      "Driver pages: Poles and Fastest Laps stats now populated",
      "Driver pages: Death date no longer shown for living drivers",
      "Constructor pages: Blank constructor names fixed (COALESCE fallback to shortName)",
      "Comparison pages: Styling restored (CSS hash patching on cached pages)",
      "Comparison pages: Races rows removed",
      "Comparison pages: Qualifying head-to-head added",
    ],
  },
  {
    version: "v6.0.5beta",
    changes: [
      "Drivers: Nationality column replaced with flag icon (hover to see name)",
      "Drivers: Championship stars shown next to driver name (★ per title)",
      "Drivers: Championships column added (sortable)",
      "Driver pages: Championships, Poles and Fastest Laps added to stats",
    ],
  },
  {
    version: "v6.0.4beta",
    changes: [
      "Drivers: Poles and Fastest Laps columns added",
      "Drivers: Current drivers filter toggle (default: all)",
      "Drivers: Fixed spurious 0s appearing after driver name badges",
    ],
  },
  {
    version: "v6.0.3beta",
    changes: [
      "Drivers: Sortable columns (click any header to sort)",
      "Drivers: Indy 500 filter — excluded by default, toggle to include",
    ],
  },
  {
    version: "v6.0.1beta",
    changes: [
      "Records: Added 2026 points system column to Most Points table",
      "Records: Sortable columns on Most Points table",
      "Constructor pages: Team History section showing full name lineage with year ranges",
      "Upcoming Features & Kanban board pages",
    ],
  },
  {
    version: "v6.00beta",
    changes: [
      "Page footer with copyright, contact, and version number",
    ],
  },
];

export const deployedTasks = sections.flatMap((s) =>
  s.tasks.filter((t) => t.status === "deployed").map((t) => ({ ...t, section: s.label }))
);

export const done: { id: string; title: string; version: string }[] = [
  { id: "KF1-D-ENH-12", title: "Rank boxes link to records page", version: "v6.3.2" },
  { id: "KF1-D-ENH-13", title: "Consistent column spacing on driver pages", version: "v6.3.2" },
  { id: "KF1-D-ENH-17", title: "Running points total and championship position in expanded season rows", version: "v6.3.2" },
  { id: "KF1-C-11", title: "Season table: indicate WDC and WCC champions", version: "v6.3.2" },
  { id: "KF1-C-14", title: "Season table: add WDC and WCC championship positions", version: "v6.3.2" },
  { id: "KF1-S-ENH-02", title: "Show points scoring system per season", version: "v6.3.2" },
  { id: "KF1-S-01", title: "Champion wins and points", version: "v6.3.2" },
  { id: "KF1-DI-04", title: "List races with missing pole times", version: "2 Jul 2026" },
  { id: "KF1-2026-R08", title: "Enter results: R8 Austrian GP (28 Jun)", version: "1 Jul 2026" },
  { id: "KF1-DI-05", title: "List races with missing fastest laps", version: "1 Jul 2026" },
  { id: "KF1-DI-06", title: "Find drivers with missing nationality code", version: "1 Jul 2026" },
  { id: "KF1-DI-10", title: "Find races with no recorded winner", version: "1 Jul 2026" },
  { id: "KF1-R-01", title: "Full list pages per record", version: "v6.3.0" },
  { id: "KF1-R-03", title: "Reformat records page into categories", version: "v6.3.1" },
  { id: "KF1-2026-R07", title: "Enter results: R7 Spanish GP (14 Jun)", version: "14 Jun 2026" },
  { id: "KF1-COMP-ENH-05", title: "Versus all teammates page", version: "v6.1.0" },
  { id: "KF1-COMP-ENH-04", title: "Race count next to year on comparison page", version: "v6.1.0" },
  { id: "KF1-COMP-ENH-03", title: "Add finishing position comparison", version: "v6.1.0" },
  { id: "KF1-COMP-BUG-02", title: "Bug: Some comparison pages returning 404", version: "v6.1.0" },
  { id: "KF1-DI-15", title: "Find comparison pages that return 404", version: "v6.1.0" },
  { id: "KF1-C-06", title: "Simplify multi-line displays", version: "v6.0.12beta" },
  { id: "KF1-C-08", title: "Season stats broken down by driver", version: "v6.0.12beta" },
  { id: "KF1-C-09", title: "Add ranks", version: "v6.0.12beta" },
  { id: "KF1-S-ENH-01", title: "Show championship leader for current season", version: "v6.0.11beta" },
  { id: "KF1-C-01", title: "Make columns sortable", version: "v6.0.10beta" },
  { id: "KF1-C-02", title: "Add filters", version: "v6.0.10beta" },
  { id: "KF1-C-03", title: "Flag icons", version: "v6.0.10beta" },
  { id: "KF1-C-04", title: "Champion icons", version: "v6.0.10beta" },
  { id: "KF1-C-07", title: "Full names and short names", version: "v6.0.10beta" },
  { id: "KF1-D-BUG-06", title: "Bug: Incorrect nationality text for some drivers", version: "v6.0.8beta" },
  { id: "KF1-D-ENH-05", title: "Default sort by last name on drivers list", version: "v6.0.8beta" },
  { id: "KF1-D-ENH-06", title: "Wrap championship stars onto two rows for 5+ titles", version: "v6.0.8beta" },
  { id: "KF1-D-ENH-07", title: "First/last race as text with full race name", version: "v6.0.8beta" },
  { id: "KF1-D-ENH-08", title: "Championships box on its own row above stats", version: "v6.0.8beta" },
  { id: "KF1-COMP-BUG-03", title: "Bug: Comparison page styling not applied", version: "v6.0.8beta" },
  { id: "KF1-D-BUG-03", title: "Bug: Senna shows 2 championships (should be 3)", version: "v6.0.7beta" },
  { id: "KF1-D-ENH-03", title: "Teammates per year in season table", version: "v6.0.7beta" },
  { id: "KF1-D-ENH-04", title: "Championship position in season table", version: "v6.0.7beta" },
  { id: "KF1-D-BUG-02", title: "Bug: Flag icons not showing", version: "v6.0.6beta" },
  { id: "KF1-D-BUG-04", title: "Bug: No numbers in poles/fastest laps on driver page", version: "v6.0.6beta" },
  { id: "KF1-D-BUG-05", title: "Bug: Death date showing for living drivers", version: "v6.0.6beta" },
  { id: "KF1-D-FIX-01", title: "Fix: Championship stars in own left column", version: "v6.0.6beta" },
  { id: "KF1-D-FIX-02", title: "Fix: Remove number next to stars on driver page", version: "v6.0.6beta" },
  { id: "KF1-D-ENH-01", title: "Flag icon on driver detail page", version: "v6.0.6beta" },
  { id: "KF1-D-ENH-02", title: "Current/Indy indicator on driver page", version: "v6.0.6beta" },
  { id: "KF1-C-BUG-01", title: "Bug: Some constructor names not showing", version: "v6.0.6beta" },
  { id: "KF1-COMP-BUG-01", title: "Bug: Comparison page lost styling", version: "v6.0.6beta" },
  { id: "KF1-COMP-ENH-01", title: "Remove races rows from comparison table", version: "v6.0.6beta" },
  { id: "KF1-COMP-ENH-02", title: "Add qualifying comparison", version: "v6.0.6beta" },
  { id: "KF1-D-05", title: "Flag icons", version: "v6.0.5beta" },
  { id: "KF1-D-08", title: "Champion icons", version: "v6.0.5beta" },
  { id: "KF1-D-09", title: "Championships count", version: "v6.0.5beta" },
  { id: "KF1-D-02", title: "Filter to current drivers", version: "v6.0.4beta" },
  { id: "KF1-D-06", title: "Poles column", version: "v6.0.4beta" },
  { id: "KF1-D-07", title: "Fastest laps column", version: "v6.0.4beta" },
  { id: "KF1-D-BUG-01", title: "Bug: Spurious 0s after driver names", version: "v6.0.4beta" },
  { id: "KF1-D-01", title: "Make columns sortable", version: "v6.0.3beta" },
  { id: "KF1-D-03", title: "Filter Indy 500 drivers out", version: "v6.0.3beta" },
  { id: "KF1-D-04", title: "Add page footer", version: "v6.00beta" },
];
